/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Courses;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class CoursesRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CoursesRegistrationJPanel
     */
    
    javax.swing.JPanel CardSequenceJPanel;
    Business business;
    RegistrationInformationJPanel registrationInfoJPanel;
    
    
    public CoursesRegistrationJPanel(Business b, JPanel cardSequenceJPanel) {
        initComponents();
        this.CardSequenceJPanel = cardSequenceJPanel;
        business = b;
        this.registrationInfoJPanel = registrationInfoJPanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistration = new javax.swing.JLabel();
        btnBrowseClasses = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRegisterForClasses = new javax.swing.JButton();
        btnRegistrationInformation = new javax.swing.JButton();

        lblRegistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistration.setText("Registration");

        btnBrowseClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBrowseClasses.setText("Browse Classes");
        btnBrowseClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseClassesActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRegisterForClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegisterForClasses.setText("Register for Classes");
        btnRegisterForClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterForClassesActionPerformed(evt);
            }
        });

        btnRegistrationInformation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrationInformation.setText("Registration Information");
        btnRegistrationInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegisterForClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrowseClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrationInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(64, 64, 64)
                .addComponent(btnBrowseClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnRegisterForClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnRegistrationInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        CardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardLayout.previous(CardSequenceJPanel);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBrowseClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseClassesActionPerformed
        // TODO add your handling code here:
        
        BrowseClassesJPanel browseclasses = new BrowseClassesJPanel(business, CardSequenceJPanel);
        
        CardSequenceJPanel.add("Browse Classes", browseclasses);
        ((java.awt.CardLayout) CardSequenceJPanel.getLayout()).next(CardSequenceJPanel);
    }//GEN-LAST:event_btnBrowseClassesActionPerformed

    private void btnRegisterForClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterForClassesActionPerformed
        // TODO add your handling code here:
        RegisterForClassesJPanel registerforclasses = new RegisterForClassesJPanel(business, CardSequenceJPanel, registrationInfoJPanel);
        
        CardSequenceJPanel.add("Register For Classes", registerforclasses);
        ((java.awt.CardLayout) CardSequenceJPanel.getLayout()).next(CardSequenceJPanel);
        
    }//GEN-LAST:event_btnRegisterForClassesActionPerformed

    private void btnRegistrationInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationInformationActionPerformed
        // TODO add your handling code here:
        
        RegistrationInformationJPanel registrationInformation = new RegistrationInformationJPanel(business, CardSequenceJPanel);
        
        CardSequenceJPanel.add("Registeration Information", registrationInformation);
        ((java.awt.CardLayout) CardSequenceJPanel.getLayout()).next(CardSequenceJPanel);
    }//GEN-LAST:event_btnRegistrationInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowseClasses;
    private javax.swing.JButton btnRegisterForClasses;
    private javax.swing.JButton btnRegistrationInformation;
    private javax.swing.JLabel lblRegistration;
    // End of variables declaration//GEN-END:variables
}
