/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Courses;

import Business.Business;
import Business.CourseCatalog.Course;
import Business.CourseSchedule.CourseOffer;
import Business.CourseSchedule.CourseSchedule;
import Business.Profiles.FacultyProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class RegisterForClassesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseWorkJPanel
     */
    javax.swing.JPanel CardSequenceJPanel;
    Business business;
    Course course;
    CourseOffer courseOffer;
    RegistrationInformationJPanel registrationInfoJPanel;
    
    
    public RegisterForClassesJPanel(Business b, JPanel CardSequenceJPanel, RegistrationInformationJPanel registrationInfoJPanel) {
        initComponents();
        this.CardSequenceJPanel = CardSequenceJPanel;
        business = b;
        this.registrationInfoJPanel = registrationInfoJPanel;
        populateCoursesTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseWork = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegisterCourses = new javax.swing.JTable();
        btnRegisterCourses = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        lblCourseWork.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCourseWork.setText("Register For Classes");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Name", "Course Number", "Faculty", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        btnAddCourse.setText("<<Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        tblRegisterCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Name", "Course Number", "Faculty", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRegisterCourses);
        if (tblRegisterCourses.getColumnModel().getColumnCount() > 0) {
            tblRegisterCourses.getColumnModel().getColumn(0).setResizable(false);
            tblRegisterCourses.getColumnModel().getColumn(2).setResizable(false);
            tblRegisterCourses.getColumnModel().getColumn(3).setResizable(false);
        }

        btnRegisterCourses.setText("Register Courses");
        btnRegisterCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCoursesActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(lblCourseWork)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegisterCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCourse))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseWork)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCourse)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterCourses)
                    .addComponent(btnRemove))
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        CardSequenceJPanel.remove(this);
        CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
        cardLayout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel coursesModel = (DefaultTableModel) tblCourses.getModel();
        DefaultTableModel registerCoursesModel = (DefaultTableModel) tblRegisterCourses.getModel();
//        registerCoursesModel.setRowCount(0); 
        
        int selectedRow = tblCourses.getSelectedRow();
        
        if (selectedRow != -1) {
            Object[] row = new Object[4];
            for (int i = 0; i < 4; i++) {
                row[i] = coursesModel.getValueAt(selectedRow, i);
            }
            
            registerCoursesModel.insertRow(0, row);
        }

    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel registerCoursesModel = (DefaultTableModel) tblRegisterCourses.getModel();
        
        int selectedRow = tblRegisterCourses.getSelectedRow();
        
        if(selectedRow != -1) {
            registerCoursesModel.removeRow(selectedRow);
        }
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRegisterCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCoursesActionPerformed
        // TODO add your handling code here:
//        DefaultTableModel registerCoursesModel = (DefaultTableModel) tblRegisterCourses.getModel();
//        registrationInfoJPanel.updateRegistrationInfoTable(registerCoursesModel);

        DefaultTableModel registerCoursesModel = (DefaultTableModel) tblRegisterCourses.getModel();
        
        if(registrationInfoJPanel == null) {
            registrationInfoJPanel = new RegistrationInformationJPanel(business, CardSequenceJPanel);
            
            CardSequenceJPanel.add(registrationInfoJPanel);
            
            //CardLayout cardLayout = (CardLayout) CardSequenceJPanel.getLayout();
//            cardLayout.next(CardSequenceJPanel);
        }
        
        registrationInfoJPanel.updateRegistrationInfoTable(registerCoursesModel);

        
        JOptionPane.showMessageDialog(null, "Registered Courses Successfully!");
    }//GEN-LAST:event_btnRegisterCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterCourses;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseWork;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTable tblRegisterCourses;
    // End of variables declaration//GEN-END:variables
        private void populateCoursesTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
        model.setRowCount(0);    
        
        
       CourseSchedule courseSchedule = business.getCourseSchedule();
       
       for(CourseOffer courseOffer : courseSchedule.getSchedule()){
           Course course = courseOffer.getSubjectCourse();
           FacultyProfile faculty = courseOffer.getFacultyProfile();
           
           Object[] row = new Object[4];
           row[0] = course.getName();
           row[1] = course.getCourseNumber();
           row[2] = (faculty != null) ? faculty.getPerson().getName() : "Not Assigned";
           row[3] = course.getCredits();
           
           model.addRow(row);
           
       }

        

        
    }


}
