/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Person.Person;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;

    public AdminUserAccount(UserAccount sua, JPanel jp) {

        CardSequencePanel = jp;
        selecteduseraccount= sua;
        initComponents();
        //display user details here
        updateUserDetails(selecteduseraccount);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblUserAccountDetails = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setLayout(null);

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(270, 390, 100, 22);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Administer User Account");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 390, 100, 22);

        lblUserAccountDetails.setText("User Account Details:");
        add(lblUserAccountDetails);
        lblUserAccountDetails.setBounds(20, 60, 150, 16);

        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(170, 110, 60, 16);

        txtName.setEditable(false);
        add(txtName);
        txtName.setBounds(270, 110, 130, 22);

        lblUserID.setText("User ID:");
        add(lblUserID);
        lblUserID.setBounds(170, 150, 50, 16);

        txtUserID.setEditable(false);
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });
        add(txtUserID);
        txtUserID.setBounds(270, 150, 130, 22);

        lblUsername.setText("Username:");
        add(lblUsername);
        lblUsername.setBounds(170, 190, 70, 16);

        txtUsername.setEditable(false);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(270, 190, 130, 22);

        lblPassword.setText("Password:");
        add(lblPassword);
        lblPassword.setBounds(170, 230, 80, 16);

        txtPassword.setEditable(false);
        add(txtPassword);
        txtPassword.setBounds(270, 230, 130, 22);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(500, 390, 72, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        txtName.setEditable(true);
        txtUserID.setEditable(true);
        txtUsername.setEditable(true);
        txtPassword.setEditable(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

//        CardSequencePanel.remove(this);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
//        saveChanges();

        String newName = txtName.getText();
        String newUserID = txtUserID.getText();
        String newUsername = txtUsername.getText();
        String newPassword = txtPassword.getText();  
        
        if (selecteduseraccount != null) {
        selecteduseraccount.getAssociatedPersonProfile().getPerson().setName(newName);
        selecteduseraccount.getAssociatedPersonProfile().getPerson().setPersonId(newUserID);
        selecteduseraccount.setUserLoginName(newUsername);
        selecteduseraccount.setPassword(newPassword);
    }
        
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);
        
        JOptionPane.showMessageDialog(null, "User Details Updated Successfully!");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserAccountDetails;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    protected void updateUserDetails(UserAccount selecteduseraccount) {
        if(selecteduseraccount != null) {
            txtName.setText(selecteduseraccount.getAssociatedPersonProfile().getPerson().getName());
            txtUserID.setText(selecteduseraccount.getAssociatedPersonProfile().getPerson().getPersonId());
            txtUsername.setText(selecteduseraccount.getUserLoginName());
            txtPassword.setText(selecteduseraccount.getPassword());
        } else {
            clearUserDetails();
        }
    }

    private void clearUserDetails() {
        txtName.setText("");
        txtUserID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }





}
